#!/usr/bin/env ruby

require 'digest'

doorid = File.read("input").chomp

idx = 0
password = ""

while password.length < 8 do
  dig = Digest::MD5.hexdigest("#{doorid}#{idx}")
  password << dig[5] if dig[0...5] == "00000"
  idx += 1
end

puts password
