#!/usr/bin/env ruby

input = File.read("input")
moves = input.split(",").map(&:strip)

x = 0
y = 0
facing = [0, 1, 0, -1]

class Array
  def rotate_left
    self.push(self.shift)
  end
  def rotate_right
    self.unshift(self.pop)
  end
end

moves.each do |move|
  turn = move[0]
  dist = move[1..-1].to_i

  case turn
  when "L"
    facing.rotate_right
  when "R"
    facing.rotate_left
  end

  x += facing[0] * dist
  y += facing[1] * dist
end

puts x.abs + y.abs
