#!/usr/bin/env ruby

require 'pp'

commands = File.readlines("input")

screen = []

6.times do
  screen << ([false]*50)
end

commands.each do |command|
  bits = command.split
  if bits[0] == "rect" then
    len, high = bits[1].split("x").map(&:to_i)
    (0...high).each do |row|
      (0...len).each do |col|
        screen[row][col] = true
      end
    end
  elsif bits[1] == "row" then
    row = bits[2].split("=").last.to_i
    times = bits[4].to_i
    times.times do
      screen[row].unshift(screen[row].pop)
    end
  else
    col = bits[2].split("=").last.to_i
    times = bits[4].to_i
    times.times do
      newcol = []
      screen.each do |r|
        newcol << r[col]
      end
      newcol.unshift(newcol.pop)
      screen.each do |r|
        r[col] = newcol.shift
      end
    end
  end
end

def hash(chunk)
  val = 0
  chunk.flatten.each do |bit|
    val <<= 1
    val += 1 if bit
  end
  val
end

#This was hard-coded using the commented line below
font = {
  422068812  => "C",
  623856210  => "H",
  203491916  => "J",
  625758866  => "K",
  554189342  => "L",
  959017488  => "P",
  959017618  => "R",
  588583044  => "Y",
  1008869918 => "Z"
}

(0...50).step(5).each do |s|
  h = hash(screen.map{|r|r[s...s+5]})
  print font[h]
  #puts h
end
puts
