#!/usr/bin/env ruby

istrs = File.readlines("input")

pad = [
  [-1, -1, -1, -1, -1, -1, -1],
  [-1, -1, -1,  5, -1, -1, -1],
  [-1, -1,  2,  6, 10, -1, -1],
  [-1,  1,  3,  7, 11, 13, -1],
  [-1, -1,  4,  8, 12, -1, -1],
  [-1, -1, -1,  9, -1, -1, -1],
  [-1, -1, -1, -1, -1, -1, -1]
]
x = 3
y = 3

code = ""

istrs.each do |istr|
  moves = istr.chars
  moves.each do |move|
    case move
    when "U"
      y -= 1 unless pad[x][y-1] == -1
    when "D"
      y += 1 unless pad[x][y+1] == -1
    when "L"
      x -= 1 unless pad[x-1][y] == -1
    when "R"
      x += 1 unless pad[x+1][y] == -1
    end
  end

  code << pad[x][y].to_s(16)
end

puts code.upcase
